export const jobTypes = [
    "Banking Operations",
    "General Insurance",
    "Investment Banking, Private Equity & VC",
    "Lending",
    "Life Insurance",
    "Trading, Asset & Wealth Management",
    "Treasury & Forex",
    "BFSI, Investments & Trading - Other",
    "After Sales Service & Repair",
    "Back Office",
    "Customer Success",
    "Non Voice",
    "Operations",
    "Operations Support",
    "Service Delivery",
    "Voice / Blended",
    "Customer Success, Service & Operations - Other",
    "Business Intelligence & Analytics",
    "Data Science & Machine Learning",
    "Data Science & Analytics - Other",
    "Hardware",
    "IT Network",
    "Telecom",
    "Hardware and Networks - Other",
    "DBA / Data warehousing",
    "DevOps",
    "Quality Assurance and Testing",
    "Software Development",
    "Accounting & Taxation",
    "Audit & Control",
    "Finance",
    "Payroll & Transactions",
    "Treasury",
    "Finance & Accounting - Other",
    "Compensation & Benefits",
    "Employee Relations",
    "HR Business Advisory",
    "HR Operations",
    "Recruitment & Talent Acquisition",
    "Recruitment Marketing & Branding",
    "Human Resources - Other",
    "IT Infrastructure Services",
    "IT Security",
    "IT Support",
    "IT & Information Security - Other",
    "Advertising & Creative",
    "Corporate Communication",
    "Digital Marketing",
    "Market Research & Insights",
    "Marketing",
    "Marketing and Communication - Other",
    "Product Management",
    "Engineering",
    "Management",
    "Operations, Maintenance & Support",
    "Production & Manufacturing - Other",
    "Construction / Manufacturing",
    "Technology / IT",
    "Other Program / Project Management",
    "Business Process Quality",
    "Production & Manufacturing",
    "Quality Assurance - Other",
    "BD / Pre Sales",
    "Enterprise & B2B Sales",
    "Retail & B2C Sales",
    "Sales Support & Operations",
    "Architecture & Interior Design",
    "Fashion & Accessories",
    "UI / UX",
    "Other Design",
    "Administration",
    "Facility Management",
    "Airline Services",
    "Aviation Engineering",
    "Flight & Airport Operations",
    "Pilot",
    "Aviation & Aerospace - Other",
    "Construction Engineering",
    "Surveying",
    "IT Consulting",
    "Management Consulting",
    "Other Consulting",
    "Content Management (Print / Online / Electronic)",
    "Editing (Print / Online / Electronic)",
    "Journalism",
    "Content, Editorial & Journalism - Other",
    "CSR & Sustainability",
    "Social & Public Service",
    "Downstream",
    "Midstream",
    "Mining",
    "Power Generation",
    "Power Supply and Distribution",
    "Upstream",
    "Energy & Mining - Other",
    "Community Health & Safety",
    "Occupational Health & Safety",
    "Environment Health and Safety - Other",
    "Events & Banquet",
    "F&B Service",
    "Front Office & Guest Services",
    "Housekeeping & Laundry",
    "Kitchen / F&B Production",
    "Tourism Services",
    "Food, Beverage & Hospitality - Other",
    "Doctor",
    "Health Informatics",
    "Imaging & Diagnostics",
    "Nursing",
    "Healthcare & Life Sciences - Other",
    "Other Hospital Staff",
    "Corporate Affairs",
    "Crime / Arbitration",
    "Legal Operations",
    "Legal & Regulatory - Other",
    "Legal Rights - Other",
    "Animation / Effects",
    "Artists",
    "Direction",
    "Editing",
    "Make Up / Costume",
    "Production",
    "Sound / Light / Technical Support",
    "Media Production & Entertainment - Other",
    "Category Management & Operations",
    "eCommerce Operations",
    "Merchandising & Planning",
    "Retail Store Operations",
    "Merchandising, Retail & eCommerce - Othe",
    "Import & Export",
    "Procurement & Purchase",
    "SCM & Logistics",
    "Stores & Material Management",
    "Procurement & Supply Chain - Other",
    "Engineering & Manufacturing",
    "Pharmaceutical & Biotechnology",
    "Research & Development - Other",
    "Assessment / Advisory",
    "Business",
    "Operations / Strategy",
    "Security / Fraud",
    "Risk Management & Compliance - Other",
    "Security Officer",
    "Security Services - Other",
    "Port & Maritime Operations",
    "Shipping Deck",
    "Shipping Engineering & Technical",
    "Shipping & Maritime - Other",
    "Beauty & Personal Care",
    "Health & Fitness",
    "Sports Science & Medicine",
    "Sports Staff and Management",
    "Sports, Fitness & Personal Care - Other",
    "Strategic Management",
    "Top Management",
    "Strategic & Top Management - Other",
    "Administration & Staff",
    "Corporate Training",
    "Language Teacher",
    "Life Skills / ECA Teacher",
    "Preschool & Primary Education",
    "Subject / Specialization Teacher",
    "University Level Educator",
    "Teaching & Training - Other"
  ]

export const jobType = ["In Office","Internship"];